version: '3.4'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    links:
      - db
    environment:
      - DB_URI=mongodb://db:27017


  db:
    image: mongo
    ports:
      - "27017:27017"
    restart: always

