// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"
	model "projeto-star-wars-api-go/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// Planet is an autogenerated mock type for the Planet type
type Planet struct {
	mock.Mock
}

// DeleteById provides a mock function with given fields: ctx, id
func (_m *Planet) DeleteById(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindById provides a mock function with given fields: ctx, id
func (_m *Planet) FindById(ctx context.Context, id string) (*model.PlanetOut, error) {
	ret := _m.Called(ctx, id)

	var r0 *model.PlanetOut
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.PlanetOut); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.PlanetOut)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByParam provides a mock function with given fields: ctx, param
func (_m *Planet) FindByParam(ctx context.Context, param *model.PlanetIn) ([]model.PlanetOut, error) {
	ret := _m.Called(ctx, param)

	var r0 []model.PlanetOut
	if rf, ok := ret.Get(0).(func(context.Context, *model.PlanetIn) []model.PlanetOut); ok {
		r0 = rf(ctx, param)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.PlanetOut)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *model.PlanetIn) error); ok {
		r1 = rf(ctx, param)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: parentContext, planet
func (_m *Planet) Save(parentContext context.Context, planet *model.PlanetIn) (string, error) {
	ret := _m.Called(parentContext, planet)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, *model.PlanetIn) string); ok {
		r0 = rf(parentContext, planet)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *model.PlanetIn) error); ok {
		r1 = rf(parentContext, planet)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, p, id
func (_m *Planet) Update(ctx context.Context, p model.PlanetIn, id string) error {
	ret := _m.Called(ctx, p, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.PlanetIn, string) error); ok {
		r0 = rf(ctx, p, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
