// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// SwapiInterface is an autogenerated mock type for the SwapiInterface type
type SwapiInterface struct {
	mock.Mock
}

// CountPlanetAppearancesOnMovies provides a mock function with given fields: ctx, planetName
func (_m *SwapiInterface) CountPlanetAppearancesOnMovies(ctx context.Context, planetName string) (int, error) {
	ret := _m.Called(ctx, planetName)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, planetName)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, planetName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
