// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// HealthChecker is an autogenerated mock type for the HealthChecker type
type HealthChecker struct {
	mock.Mock
}

// Check provides a mock function with given fields: ctx
func (_m *HealthChecker) Check(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
